### ISSUE TITLE
Parent initializer not emitted even though arguments present

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-transpiler#78]
In the code introduced in #74 we're removing grandparents too eagerly.

In the following code the arguments for `A` are available in `C`, yet the initializer for `A` is not called because it's a parent of the uninitialized `B`.

```solidity
contract A {
    constructor(uint x) public {}
}

abstract contract B is A {
    constructor(uint y) public {}
}

abstract contract C is A, B {
    constructor(uint z) A(z) public {}
}
```

Expected output for C:

```solidity
function __C_init(uint z) {
  __A_init_unchained(z);
  __C_init_unchained(z);
}
```

The call to `__A_init_unchained` is not currently being emitted.

**Comment by JulissaDantes** [comment]
This is going to be fixed once the PR #79 is merge
